### ISSUE TITLE
React.js: questions

### ISSUE THREAD

**Issue by bookstein** [bookstein/learning_grid#12]
## Questions based on React tutorial

Tutortial: https://facebook.github.io/react/docs/tutorial.html
- "The `div` tags are not actual DOM nodes; they are instantiations of React div components. You can think of these as markers or pieces of data that React knows how to handle." What does it mean by instantiations of React div components? that "Div" is a class name and can be used to build new divs?
- What's the best way to debug React, if the word "debugger" is just rendered as text from within a component? (Partial answer: [React dev tools](https://facebook.github.io/react/blog/2014/01/02/react-chrome-developer-tools.html))

**Comment by keighty** [comment]
I think this is a useful post to get us started: https://facebook.github.io/react/docs/getting-started.html
as well as https://www.twilio.com/blog/2015/08/setting-up-react-for-es6-with-webpack-and-babel-2.html

(should cut down on the boilerplate, and make it so that we can use the latest and greatest javascripts)

this pr to my test project has some helpful modifications: https://github.com/keighty/virtual_playbill/pull/1
